### ISSUE TITLE
Add CONTRIBUTING.md

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#1]
Example: https://github.com/hwchase17/langchainjs/blob/main/CONTRIBUTING.md

**Comment by krishaajtak** [comment]
Really great initiative. Dart Port of Langchain can really be an asset. I will be really happy to help.

**Comment by davidmigloz** [comment]
Hey @krishaajtak 

Thanks for offering to help! 

I'm setting up the foundations of the project and creating some issues with TODOs.
Feel free to pick some of them (or anything else you would like to help with!).

Cheers.

**Comment by davidmigloz** [comment]
Done https://github.com/davidmigloz/langchain_dart/blob/main/CONTRIBUTING.md
