### ISSUE TITLE
Integrate Ollama LLMs

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#102]
https://github.com/jmorganca/ollama

Ollama is sort of like Docker for models.

Install a desktop app and quickly run a GPU-optimized open-source LLM (including uncensored variants) from a `Modelfile` on your local machine.

https://twitter.com/Hacubu/status/1688573589380005890?s=20

https://github.com/hwchase17/langchainjs/blob/main/langchain/src/llms/ollama.ts

**Comment by mthongvanh** [comment]
hi david, can you please assign this ticket to me. i will start by researching generating an ollama api client from an open api spec.

**Comment by walsha2** [comment]
@mthongvanh it does not look like there is an ollama OpenAPI spec defined, however it looks like it has been requested: https://github.com/jmorganca/ollama/issues/716

If there is one, or you manually write one, you can use the [openapi_spec](https://pub.dev/packages/openapi_spec) to easily generate a client and schema files. 

-----------

There are a couple of examples in `langchain_dart` for the Chroma client and the Open AI client:

https://github.com/davidmigloz/langchain_dart/blob/ab12b2fcf6edbe9d8102c97319f06ba0815fc3d0/packages/chromadb/oas/main.dart#L3-L21

https://github.com/davidmigloz/langchain_dart/blob/ab12b2fcf6edbe9d8102c97319f06ba0815fc3d0/packages/openai_dart/oas/main.dart#L3-L8

**Comment by davidmigloz** [comment]
Hey @walsha2 !

I didn't find any openapi spec either. But I've aligned with @mthongvanh to manually write one and rewrite his initial implementation of the Ollama client using [openapi_spec](https://pub.dev/packages/openapi_spec). He should be almost done with it.

Btw @mthongvanh, make sure to update to the latest version, there was one issue with the responses decoding logic ([ref](https://github.com/tazatechnology/openapi_spec/issues/43)).

**Comment by mthongvanh** [comment]
@davidmigloz sounds good. indeed it would be nice to have a spec, even if we need to modify them to get nicer models generated from openapi_spec. i updated and pushed up the api client code to my fork. i'll start working on the langchain integration next, so we might need to connect on that. [https://github.com/mthongvanh/langchain_dart/tree/feature/102-integrate-ollama-llms](https://github.com/mthongvanh/langchain_dart/tree/feature/102-integrate-ollama-llms)

@walsha2 i did run into one issue when generating paths with responses that have no content. the generated client returns void on success which i dont think is ideal. i can open an issue on openapi_spec and we can discuss there. great job on proj btw!

**Comment by walsha2** [comment]
> i did run into one issue when generating paths with responses that have no content. the generated client returns void on success which i dont think is ideal. i can open an issue on openapi_spec and we can discuss there. great job on proj btw!

`void` is the default now if there is no returned content, that is correct. The only other thing I can think of that would make some sense is the full http `Response` object? Is that more ideal? Anyway, yes, feel free to open an issue! Open to suggestions.

**Comment by davidmigloz** [comment]
[ollama_dart](https://pub.dev/packages/ollama_dart) released! 🚀

**Comment by mthongvanh** [comment]
w00t w00t!

**Comment by davidmigloz** [comment]
`langchain_ollama v0.0.1` released with support for `Ollama`, `ChatOllama` and `OllamaEmbeddings` 🥳
