### ISSUE TITLE
Support ConversationalRetrievalQAChain

### ISSUE THREAD

**Issue by mirkancal** [davidmigloz/langchain_dart#108]
### Feature request

https://js.langchain.com/docs/modules/chains/popular/chat_vector_db

### Motivation

Having conversation context for RetrievalQAChain.

### Your contribution

I'm getting more familiar with library, I'll update if I'll have a PR.

**Comment by mdshihabuddinroky** [comment]
Please add this as soon as possible. Thank you

**Comment by davidmigloz** [comment]
Duplicate of #52
