### ISSUE TITLE
Support for custom base_api

### ISSUE THREAD

**Issue by JackuXL** [davidmigloz/langchain_dart#124]
### Feature request

Custom the base_api url for OpenAI

### Motivation

I use [OneAPI](https://github.com/songquanpeng/one-api) to distribute api keys. It requires to sending requests to its website instead of the official URL.

### Your contribution

Hmmm

**Comment by davidmigloz** [comment]
hey @JackuXL ,

You can create an instance of `OpenAIClient` with a different `apiBaseUrl` like this:
```
final openai = OpenAI(
  apiClient: OpenAIClient.instanceFor(
    apiKey: 'api-key',
    apiBaseUrl: 'your-api-base-url',
    organization: 'your-organization',
  ),
);
```

**Comment by JackuXL** [comment]
@davidmigloz 
Thank you for your answer🙏
Btw, I'm wondering if you have any plan for serpapi or google-search wrapper?

**Comment by davidmigloz** [comment]
@JackuXL We should definitely add support for it, but I haven't had time to implement it. Would you like to contribute?

**Comment by JackuXL** [comment]
@davidmigloz 
I'll give it a shot, but I'm not well-versed in Dart, so no promises. 😢

**Comment by davidmigloz** [comment]
Awesome! Let me know if you need some guidance 🙂
