### ISSUE TITLE
Add ability to specify user in OpenAI and ChatOpenAI 

### ISSUE THREAD

**Issue by mirkancal** [davidmigloz/langchain_dart#143]
### Feature request

https://platform.openai.com/docs/guides/safety-best-practices

It seems missing.

### Motivation

We can pass userId to OpenAI, not sure if there's any benefits except for them to monitor users.

### Your contribution

Checking how to add without breaking the code.

**Comment by davidmigloz** [comment]
thanks for reporting @mirkancal!
Let me take a quick look. It should be easy to add.

**Comment by davidmigloz** [comment]
Done!

Now you can either specify it when instantiating the wrapper if the user will be always the same:
```dart
final chat = ChatOpenAI(
  apiKey: '...', 
  user: 'user123456',
);
```

Or when calling the llm if the user varies per request:
```dart
final res = await chat(
  [query],
  options: const ChatOpenAIOptions(user: 'user123456'),
);
```

Btw, thank you very much for assisting people in our discord, I really appreciate it 🙂
