### ISSUE TITLE
Where can I get values for OPENAI_API_KEY, VERTEX_AI_SERVICE_ACCOUNT and VERTEX_AI_PROJECT?

### ISSUE THREAD

**Issue by polina-c** [davidmigloz/langchain_dart#158]
[langchain_google example](https://pub.dev/packages/langchain_google/example) wants couple env variables to be provided:
VERTEX_AI_SERVICE_ACCOUNT
VERTEX_AI_PROJECT

I created account and project in google cloud, but I do not see what should be values of these variables. Can you help?

[langchain_chroma example](https://pub.dev/packages/langchain_chroma/example) wants OPENAI_API_KEY. How can I get it?

**Comment by polina-c** [comment]
I found OPENAI_API_KEY can be created at https://platform.openai.com/account/api-keys

But pantheon is still puzzling me

**Comment by davidmigloz** [comment]
hey @polina-c !

First of all, thank you very much for the sponsor 😊

To use VertexAI you need to:

1. Create a Google Cloud project (make sure billing is enabled).
2. [Enable the Vertex AI API](https://console.cloud.google.com/flows/enableapi?apiid=aiplatform.googleapis.com).
3. Create a service account with the required permissions (you can find them in the API docs of each wrapper: [VertexAI](https://pub.dev/documentation/langchain_google/latest/langchain_google/VertexAI-class.html), [ChatVertexAI](https://pub.dev/documentation/langchain_google/latest/langchain_google/ChatVertexAI-class.html), [VertexAIEmbeddings](https://pub.dev/documentation/langchain_google/latest/langchain_google/VertexAIEmbeddings-class.html), [VertexAIMatchingEngine](https://pub.dev/documentation/langchain_google/latest/langchain_google/VertexAIMatchingEngine-class.html)).

Once you've completed the previous steps, you can jump into your code and instantiate the wrapper you need. Let's take `ChatVertexAI` as an example.

To create an instance of `ChatVertexAI` you need to provide an HTTP client that handles authentication. The easiest way to do this is to use the [googleapis_auth](https://pub.dev/packages/googleapis_auth) package:

```dart
final serviceAccountCredentials = ServiceAccountCredentials.fromJson(
  json.decode(Platform.environment['VERTEX_AI_SERVICE_ACCOUNT']!),
);
final authClient = await clientViaServiceAccount(
  serviceAccountCredentials,
  [ChatVertexAI.cloudPlatformScope],
);
final chatVertexAi = ChatVertexAI(
  httpClient: authClient,
  project: 'your-project-id',
);
```

- `VERTEX_AI_SERVICE_ACCOUNT`: is a JSON with the service account keys. You can download it from the 'Keys' section on the [service account page](https://console.cloud.google.com/iam-admin/serviceaccounts/).
- `your-project-id`: is the ID of your Google Cloud project. You can find it on the [welcome page](https://console.cloud.google.com/welcome).

Now you should be able to use `ChatVertexAI` to interact with PaLM chat.

Regarding OpenAI, indeed you can get your API key from https://platform.openai.com/account/api-keys.

I'm not sure about pantheon, are you referring to [this company](https://www.pantheonlab.ai/)? If so, we don't have an integration with them yet (unless their API is compatible with any of our existing wrappers like OpenAI).

Let me know if you get it to work!

**Comment by polina-c** [comment]
Thank you!
Never mind about pantheon. I messed internal and external things up.

**Comment by davidmigloz** [comment]
Ahh that was it 🙂

I'll keep this issue open to remind me to add to the docs how to get an OpenAI key and how to configure a Vertex AI.

Let me know if you need help with anything else!

**Comment by davidmigloz** [comment]
I've updated the API documentation and the project documentation clarifying your questions.
Let me know if you have any other doubt! For now, I'll close this issue 🙂
