### ISSUE TITLE
Example for langchain_chroma fails, because it connects to localhost.

### ISSUE THREAD

**Issue by polina-c** [davidmigloz/langchain_dart#159]
It seems right API url should be specified somewhere in example.

Steps to repro:
1. Copy [the example](https://pub.dev/packages/langchain_chroma/example) to your dart project `bin/chroma.dart`
2. Add dependencies:
```
  langchain: ^0.0.12
  langchain_openai: ^0.0.12
  langchain_google: ^0.0.7+1
  langchain_chroma: ^0.0.3
```
4. Configure OPENAI_API_KEY
5. Run `dart run bin/chroma.dart`
6. Get error:

```
Unhandled exception:
ChromaApiClientException({
  "uri": "http://localhost:8000/api/v1/collections",
  "method": "POST",
  "code": null,
  "message": "Response error",
  "body": "ClientException with SocketException: Connection refused (OS Error: Connection refused, errno = 61), address = localhost, port = 58657, uri=http://localhost:8000/api/v1/collections"
})
#0      ChromaApiClient._request (package:chromadb/src/generated/client.dart:231:7)
<asynchronous suspension>
#1      ChromaApiClient.createCollection (package:chromadb/src/generated/client.dart:367:15)
<asynchronous suspension>
#2      ChromaClient.getOrCreateCollection (package:chromadb/src/chroma_client.dart:74:17)
<asynchronous suspension>
#3      Chroma._getCollection (package:langchain_chroma/src/vector_stores/chroma.dart:179:24)
<asynchronous suspension>
#4      Chroma.addVectors (package:langchain_chroma/src/vector_stores/chroma.dart:102:24)
<asynchronous suspension>
#5      main (file:///Users/polinach/_/spikes/ai/bin/chroma.dart:14:3)
<asynchronous suspension>
```

**Comment by davidmigloz** [comment]
Hello @polina-c !

To use Chroma you need to run it in [client/server mode](https://docs.trychroma.com/usage-guide#running-chroma-in-clientserver-mode).

1. Clone the Chroma repo

```
git clone git@github.com:chroma-core/chroma.git
```

2. Run the docker container

```
docker-compose up -d --build
```

By default, it will run on `http://localhost:8000`, but if you are running it somewhere else you can change the base URL using the `host` parameter:

```dart
final openaiApiKey = Platform.environment['OPENAI_API_KEY']!;
final embeddings = OpenAIEmbeddings(apiKey: openaiApiKey);
final vectorStore = Chroma(
  embeddings: embeddings,
  host: 'http://localhost:8888',
);
```

If you are running it on a server and you need to handle authentication, you can provide your own HTTP client:
```
final vectorStore = Chroma(
  embeddings: embeddings,
  client: yourHttpClient,
);
```

Let me know if you have any other question!

(it was a good reminder that I need to update the documentation 🙂)

**Comment by davidmigloz** [comment]
I've updated the [Chroma](https://langchaindart.com/#/modules/retrieval/vector_stores/integrations/chroma) documentation. So, hopefully, this topic is now more clear!
