### ISSUE TITLE
Because langchain depends on langchain, version solving failed.

### ISSUE THREAD

**Issue by alfmirbel** [davidmigloz/langchain_dart#177]
### System Info

flutter --version
Flutter 3.13.7 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 2f708eb839 (2 weeks ago) • 2023-10-09 09:58:08 -0500
Engine • revision a794cf2681
Tools • Dart 3.1.3 • DevTools 2.25.0

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

flutter pub add langchain

### Expected behavior

Package install

**Comment by davidmigloz** [comment]
hello @alfmirbel,

Can you post the whole error message? Which dependency is conflicting? Thanks.

**Comment by alfmirbel** [comment]
Hi!
That´s the all the message after execute the instalation command

PS E:\langchain> flutter pub add langchain
Because langchain depends on langchain, version solving failed.
PS E:\langchain>

**Comment by alfmirbel** [comment]
These are the dependenciaes that I got:

PS E:\langchain> flutter pub get langchain --directory
Resolving dependencies... (4.0s)
  collection 1.17.2 (1.18.0 available)
  flutter_lints 2.0.3 (3.0.0 available)
  lints 2.1.1 (3.0.0 available)
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  test_api 0.6.0 (0.6.1 available)
  web 0.1.4-beta (0.3.0 available)
Got dependencies!

**Comment by alfmirbel** [comment]
More info:

PS E:\langchain> flutter pub upgrade langchain
Resolving dependencies... 
  async 2.11.0
  boolean_selector 2.1.1
  characters 1.3.0
  clock 1.1.1
  collection 1.17.2 (1.18.0 available)
  cupertino_icons 1.0.6
  fake_async 1.3.1
  flutter 0.0.0 from sdk flutter
  flutter_lints 2.0.3 (3.0.0 available)
  flutter_test 0.0.0 from sdk flutter
  lints 2.1.1 (3.0.0 available)
  matcher 0.12.16
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
  path 1.8.3
  sky_engine 0.0.99 from sdk flutter
  source_span 1.10.0
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  string_scanner 1.2.0
  term_glyph 1.2.1
  test_api 0.6.0 (0.6.1 available)
  vector_math 2.1.4
  web 0.1.4-beta (0.3.0 available)
No dependencies changed.
9 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

**Comment by alfmirbel** [comment]
PS E:\langchain> flutter pub outdated
Showing outdated packages.
[*] indicates versions that are not the latest available.

Package Name   Current  Upgradable  Resolvable  Latest

direct dependencies: all up-to-date.

dev_dependencies:
flutter_lints  *2.0.3   *2.0.3      3.0.0       3.0.0

1 dependency is constrained to a version that is older than a resolvable version.
To update it

**Comment by alfmirbel** [comment]
PS E:\langchain> flutter pub upgrade --major-versions
Resolving dependencies... 
  async 2.11.0
  boolean_selector 2.1.1
  characters 1.3.0
  clock 1.1.1
  collection 1.17.2 (1.18.0 available)
  cupertino_icons 1.0.6
  fake_async 1.3.1
  flutter 0.0.0 from sdk flutter
> flutter_lints 3.0.0 (was 2.0.3)
  flutter_test 0.0.0 from sdk flutter
> lints 3.0.0 (was 2.1.1)
  matcher 0.12.16
  material_color_utilities 0.5.0 (0.8.0 available)
  meta 1.9.1 (1.11.0 available)
  path 1.8.3
  sky_engine 0.0.99 from sdk flutter
  source_span 1.10.0
  stack_trace 1.11.0 (1.11.1 available)
  stream_channel 2.1.1 (2.1.2 available)
  string_scanner 1.2.0
  term_glyph 1.2.1
  test_api 0.6.0 (0.6.1 available)
  vector_math 2.1.4
  web 0.1.4-beta (0.3.0 available)
Changed 2 dependencies!
7 packages have newer versions incompatible with dependency constraints.
Try `flutter pub outdated` for more information.

Changed 1 constraint in pubspec.yaml:
  flutter_lints: ^2.0.0 -> ^3.0.0
PS E:\langchain>

**Comment by davidmigloz** [comment]
I cannot reproduce it.

Can you manually add the langchain dependencies to your `pubspec.yaml`:
```yaml
dependencies:
  #  Your other dependencies...
  langchain: 0.0.13
  langchain_openai: 0.0.13

and run `flutter pub get`?

That should give you an error message indicating the dependency that is causing issues.

**Comment by alfmirbel** [comment]
Yes. This is the resulting message:

[langchain] flutter pub get --no-example
Resolving dependencies...
Error on line 38, column 3 of pubspec.yaml: A package may not list itself as a dependency.
   ╷
38 │   langchain: 0.0.13
   │   ^^^^^^^^^
   ╵
exit code 65

**Comment by davidmigloz** [comment]
There you have the error: "A package may not list itself as a dependency". Your project cannot have the same name as some of its dependencies. Use a different project name. 
Check this video: https://www.youtube.com/watch?v=fr05X33GVhE

**Comment by alfmirbel** [comment]
Thanks a lot!!
Thanks for your time!!
