### ISSUE TITLE
Support UTF-8 characters (e.g. Hebrew)

### ISSUE THREAD

**Issue by orenagiv** [davidmigloz/langchain_dart#233]
Due to a bug in the `openapi_spec` package - if the OpenAI response include UTF-8 characters of languages such as Hebrew - the response is not properly decoded and the result is "gibberish".

This affects the `openai_dart` package.

I've opened a bug in `openapi_spec`:
https://github.com/tazatechnology/openapi_spec/issues/43

I hope they'll fix it soon.

**Comment by walsha2** [comment]
@davidmigloz this has been resolved in https://github.com/tazatechnology/openapi_spec/pull/44 and published to [`openapi_spec` (v0.7.8)](https://pub.dev/packages/openapi_spec).

**Comment by davidmigloz** [comment]
Thanks @orenagiv for reporting and @walsha2 for the quick fix!

The fix is now deployed in:
- [`openai_dart: 0.1.1+2`](https://pub.dev/packages/openai_dart/changelog#0112)
- [`langchain_openai 0.1.2+1 `](https://pub.dev/packages/langchain_openai/changelog#0121)
