### ISSUE TITLE
Add support for ConversationBufferWindowMemory class

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#25]
> It keeps in memory the number of interactions specified.
> E.g. k=1 only remembers the last input/output

https://python.langchain.com/en/latest/reference/modules/memory.html?highlight=ConversationBufferWindowMemory#langchain.memory.ConversationBufferWindowMemory

**Comment by dileep9490** [comment]
latest link: https://python.langchain.com/docs/modules/memory/how_to/buffer_window

**Comment by mauricepoirrier** [comment]
@davidmigloz i can give it a try 🙋. Any thoughts about where to start?

**Comment by davidmigloz** [comment]
@mauricepoirrier good to hear!

You can look at the original implementations:
- Python: https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/buffer_window.py
- JS: https://github.com/hwchase17/langchainjs/blob/main/langchain/src/memory/buffer_window_memory.ts

And their tests:
- Python: https://github.com/langchain-ai/langchain/blob/master/libs/langchain/tests/unit_tests/chains/test_memory.py
- JS: https://github.com/hwchase17/langchainjs/blob/main/langchain/src/memory/tests/buffer_window_memory.test.ts

Also, you can check the current `ConversationBufferMemory` Dart implementation.
- https://github.com/davidmigloz/langchain_dart/blob/main/packages/langchain/lib/src/memory/buffer.dart

And based on those you can create the Dart implementation.
- Implementation: `packages/langchain/lib/src/memory/buffer_window.dart`
- Tests: `packages/langchain/test/memory/buffer_window.dart`

Let me know if you have any questions 🙂
