### ISSUE TITLE
Add support for ConversationTokenBufferMemory class

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#26]
> It limits the number of tokens (which is normally how you get billed when calling the LLM)

https://python.langchain.com/en/latest/reference/modules/memory.html?highlight=ConversationTokenBufferMemory#langchain.memory.ConversationTokenBufferMemory

**Comment by davidmigloz** [comment]
Awesome! 

The equivalent of Python LangChain's `llm.get_num_tokens_from_messages(buffer)` method is `llm.countTokens(PromptValue.chat(buffer))`. The rest you should already be familiar with from the previous PR 🙂

Let me know if you have any doubt.

**Comment by orenagiv** [comment]
Hey @davidmigloz 
Is there a reason why `token_buffer.dart` is not exported by `memory.dart`?

**Comment by davidmigloz** [comment]
Hmm indeed, it is not exported. Thanks for reporting!

Fixed (https://github.com/davidmigloz/langchain_dart/pull/280)

**Comment by davidmigloz** [comment]
Released in [0.3.1+1](https://pub.dev/packages/langchain/changelog#0311)

**Comment by orenagiv** [comment]
Thanks @davidmigloz !

**Comment by orenagiv** [comment]
Hi @davidmigloz 

I have no explanation to what I'm about to describe here :)
But I've been stuck on this one for a few days already.

As soon as I've started using the `ConversationTokenBufferMemory` It worked smoothly on debug.
But when I built a release - the compilation time increased from ~5m to ~1 hour (for both Android and iOS).
(although it took ~1 hour - it eventually completed the build successfully, and it works).

Here's how I'm using it:
```
final chatOpenAi = ChatOpenAI(
  apiKey: '...',
  organization: '...',
  defaultOptions: ChatOpenAIOptions(
    temperature: 0.0,
    model: 'gpt-3.5-turbo-1106',
  ),
);

// final memory = ConversationBufferMemory(returnMessages: true);
// When using the above `ConversationBufferMemory` the release build takes ~5m.
// However, when using the `ConversationTokenBufferMemory` below - the build time jumps to 1 hour in my case...
final memory = ConversationTokenBufferMemory(
  returnMessages: true,
  llm: chatOpenAi,
);

final agent = OpenAIFunctionsAgent.fromLLMAndTools(
  llm: chatOpenAi,
  tools: tools,
  memory: memory,
);
```

Maybe I'm doing something wrong..?
Any ideas?
(let me know if I should open a separate issue for this one)

**Comment by davidmigloz** [comment]
Hmm it may be related to this issue from the `tiktoken` package: https://github.com/mvitlov/tiktoken/issues/5

I guess, before using `ConversationTokenBufferMemory`, all the `tiktoken` related code was tree-shacked, but now it's not.

Unfortunately, the author of `tiktoken` package doesn't seem to be very active anymore. There's a PR fixing the issue, but it's been months there for months. 

Maybe we should migrate to https://pub.dev/packages/flutter_tiktoken or create our own fork.

**Comment by orenagiv** [comment]
Thanks @davidmigloz !
I'm on it. 
Will keep you posted.

**Comment by davidmigloz** [comment]
Thanks for your work!

I didn't review `flutter_tiktoken` code before, but now I see that it's a flutter plugin instead of pure Dart package..
We cannot really use it, as that will prevent using LangChain.dart in backend services or CLI apps. 

I don't think there's any reason for it to be a flutter plugin, so maybe it can be refactored to a pure Dart package (as the original package was).

**Comment by orenagiv** [comment]
Got it @davidmigloz  
I'll see if I can find an alternative.

**Comment by orenagiv** [comment]
I think I'll fork the original tiktoken package with the PR that was never merged, and create a new Dart package called langchain_tiktoken that we can use. 

What do you think @davidmigloz ?

**Comment by davidmigloz** [comment]
Sounds good!

I think we can even remove most of the asset files it bundles, as we only need to support `cl100k_base` for LangChain (as all the others were used by models that are already deprecated). So it will use much less memory as well.

**Comment by orenagiv** [comment]
Hey @davidmigloz 

Done.
https://github.com/davidmigloz/langchain_dart/pull/285

Note:
It's still 'draft' as I'm still testing + haven't yet made the changes in the rest of the sub-packages (only in langchain_openai so far).
