### ISSUE TITLE
Integrate Ollama Chat API

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#260]
Ollama launched a new [chat API](https://discord.com/channels/1128867683291627614/1151557857846767656/1183480579111518268). It'd be good to migrate `ChatOllama` to use it.

> ## Ollama 0.1.14
> 
> **Chat API**: this release of Ollama includes a new Chat API for conversations with an assistant. The Chat API makes it easy integrate Ollama into chat-based applications, and enables new prompt techniques that involve a series of messages such as [Chain-of-Thought](https://www.promptingguide.ai/techniques/cot).
> 
> To use this API, call `POST /api/chat` with a history of `messages`:
> 
> ```
>  curl http://localhost:11434/api/chat -d '{
>   "model": "mistral",
>   "messages": [
>     { "role": "system", "content": "You are a helpful assistant that answers concisely." },
>     { "role": "user", "content": "why is the sky blue?" }
>   ]
> }'
> ```
> 
> The assistant's next `message` in the conversation is provided in the response (or series of responses if streaming):
> 
> ```
> {
>     "message": { "role": "assistant", "content": "The sky is blue because of the way the atmosphere scatters light." }
> }
> ```

**Comment by mthongvanh** [comment]
hey @davidmigloz can you assign this task to me?

**Comment by davidmigloz** [comment]
done!

**Comment by davidmigloz** [comment]
Let's add the image field as well 🙂
https://github.com/jmorganca/ollama/releases/tag/v0.1.15

**Comment by davidmigloz** [comment]
This is now live in [langchain_ollama 0.0.2](https://pub.dev/packages/langchain_ollama/changelog)
