### ISSUE TITLE
Add support for ConversationSummaryMemory class

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#27]
> Instead of limiting the memory of the conversation, it uses the LLM to generate a summary of it

https://python.langchain.com/en/latest/reference/modules/memory.html?highlight=ConversationSummaryMemory#langchain.memory.ConversationSummaryMemory

**Comment by dileep9490** [comment]
here's the latest link: https://python.langchain.com/docs/modules/memory/how_to/summary_buffer

**Comment by mauricepoirrier** [comment]
👋🏼 I'm going to grab this one! Any thoughts on just copy pasting the default summarize prompt? some other suggestion?

**Comment by davidmigloz** [comment]
Awesome! In the Python project, they have a [`prompt.py`](https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/memory/prompt.py) file with all the default prompts related to memory, but I think is better to have each prompt in the file where it is used so that it is easier to find. What's your opinion?

**Comment by mauricepoirrier** [comment]
I felt the same 👍🏼  So i'll do that way. Thanks! @davidmigloz
