### ISSUE TITLE
Issue Quotas with VertexAI Embeddings

### ISSUE THREAD

**Issue by eckarath-eckastudio** [davidmigloz/langchain_dart#286]
### System Info

I have the following error when I use VertexAI embeddings 
```
Error: DetailedApiRequestError(status: 429, message: Quota exceeded for aiplatform.googleapis.com/online_prediction_requests_per_base_model with base model: textembedding-gecko. Please submit a quota increase request. https://cloud.google.com/vertex-ai/docs/quotas.)
```
Limit for embeddings is 600 by minutes (see [here](https://cloud.google.com/vertex-ai/docs/quotas)) which should be enough for my usecase ...

I'll try to QA a document ...
Here is how I proceed : 

1. Load a document
```
TextLoader loader = TextLoader(filePath);
    final List<Document> documents = await loader.load();
    const RecursiveCharacterTextSplitter textSplitter = RecursiveCharacterTextSplitter(
      chunkSize: 700,
      chunkOverlap: 200,
      addStartIndex: true
    );
    final List<Document> texts = textSplitter.splitDocuments(documents);
    print("Chunk documents : ${texts.length}");
    return texts
        .mapIndexed(
          (int i, Document d) => d.copyWith(
            metadata: {
              ...d.metadata,
              "source": "$i-pl",
            },
          ),
        )
        .toList(growable: false);
     }
```

2. Create a memory vectorstore
```
    final Embeddings embeddings = await LangChainUtils.getEmbeddings();
    switch (vectorBase) {
      case VectorBase.vertexAI:

      default:
        // Create a Vector Datastore (in memory) and upload documents data
        return MemoryVectorStore.fromDocuments(
          documents: textsWithSources,
          embeddings: embeddings,
        );
    }
```

3. Create a StuffDocumentChain
```
   final prompt = PromptTemplate.fromTemplate("""
      Answer the question based only on the following context:

      {context}

      ---

      Answer the question based on the above context: {question}
      """,
    );
    final LLMChain llmChain = LLMChain(prompt: prompt, llm: llm);

    final docPrompt = PromptTemplate.fromTemplate(
      'Content: {page_content}\nSource: {source}',
    );
    return StuffDocumentsChain(llmChain: llmChain, documentPrompt: docPrompt);
```

4. Use it in a RetrievalQAChain
```
    StuffDocumentsChain chain = LangChainUtils.getQAChain(llm);
    retrievalQA = RetrievalQAChain(retriever: search.asRetriever(), combineDocumentsChain: chain);
    Map qaResult = await retrievalQA.retrievalQA("My Question");
```

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [X] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

```
flutter doctor -v
```

```
[✓] Flutter (Channel stable, 3.16.5, on macOS 13.6.3 22G436 darwin-x64, locale fr-FR)
    • Flutter version 3.16.5 on channel stable at /Users/eckarath/Development/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (3 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
```

### Expected behavior

We should be able to manage throttling api send to avoid quotas limit when using Embeddings API (batch, may be ?)

**Comment by davidmigloz** [comment]
Hey @eckarath-eckastudio,

Thanks for reporting. 

`VertexAIEmbeddings` already [batches the documents in groups of 5](https://github.com/davidmigloz/langchain_dart/blob/76b01d2376c0d9727d1f4681dba83a46f4b02b3a/packages/langchain_google/lib/src/embeddings/vertex_ai.dart#L169), which is the max batch size [according to the docs](https://arc.net/l/quote/gjnvvkxs).

When I implemented it, VertexAI was throwing an exception if you were sending a batch with more than 5 docs. I'm not sure if that's still the case, as it was a very low limit compared to other competitors. Maybe the docs are not up-to-date. Could you check if they have increased the limit? If so, I can increase the batch size.

**Comment by eckarath-eckastudio** [comment]
Sorry for the late answer ...
Batch is still 5 docs but you can easily ask to increase the quota limits into the Google Cloud Console which has solved my problem ... I have increase up to 2000 requests per minute

**Comment by davidmigloz** [comment]
Awesome, thanks for confirming.

If they increase the batch limit in the future, you can change it when instantiating `VertexAIEmbeddings`:

```dart
final embeddings = VertexAIEmbeddings(
  httpClient: authClient,
  project: 'your-project-id',
  batchSize: 2000,
);
```

Cheers.
