### ISSUE TITLE
Add support for Ollama Tools

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#288]
https://js.langchain.com/docs/integrations/chat/ollama_functions

> LangChain offers an experimental wrapper around open source models run locally via [Ollama](https://github.com/jmorganca/ollama) that gives it the same API as OpenAI Functions.

**Comment by Ganeshsivakumar** [comment]
Hi @davidmigloz  I've been working on tool calling feature for ollama, could you assign this issue to me.
