### ISSUE TITLE
Add streaming support to googleai_dart client

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#299]
Docs: https://ai.google.dev/tutorials/rest_quickstart#stream_generate_content

The schema and main methods from the client are automatically generated from the OpenAPI spec. However, the streaming methods need to be written manually.

To add stream support to generate content we need to:
1. Remove `/models/{modelId}:streamGenerateContent` from the [`googleai_openapi_curated.yaml`](https://github.com/davidmigloz/langchain_dart/blob/cff2c58a19fb7503ec17744b4edaaa4008227aa3/packages/googleai_dart/oas/googleai_openapi_curated.yaml#L1023-L1049) and [regenerate the client](https://github.com/davidmigloz/langchain_dart/blob/cff2c58a19fb7503ec17744b4edaaa4008227aa3/packages/googleai_dart/oas/main.dart) (as we will add this method manually).
2. Add a `streamGenerateContent` method in the [`GoogleAIClient`](https://github.com/davidmigloz/langchain_dart/blob/cff2c58a19fb7503ec17744b4edaaa4008227aa3/packages/googleai_dart/lib/src/client.dart) class. You can check [`OpenAIClient.createCompletionStream`](https://github.com/davidmigloz/langchain_dart/blob/cff2c58a19fb7503ec17744b4edaaa4008227aa3/packages/openai_dart/lib/src/client.dart#L61-L80) as a reference.
3. Write a `StreamTransformer` that returns valid jsons from the stream of data. You can check [`_OpenAIStreamTransformer`](https://github.com/davidmigloz/langchain_dart/blob/cff2c58a19fb7503ec17744b4edaaa4008227aa3/packages/openai_dart/lib/src/client.dart#L116-L128) as a reference (but the way the data is sent may be different).

**Comment by luisredondo** [comment]
I will work on this one! @davidmigloz
