### ISSUE TITLE
Add support for SequentialChain class

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#30]
> This is the simplest type of a sequential chain, where each step has a single input/output, and the output of one step is the input to the next.

https://python.langchain.com/en/latest/modules/chains/getting_started.html#combine-chains-with-the-sequentialchain

**Comment by ITP2023** [comment]
Hi there, I'd like to suggest this short gist I made that implements this feature. Please do review it.

https://gist.github.com/ITP2023/962bc89c2db9118d02b5950f0a11746b

**Comment by dileep9490** [comment]
latest link: https://python.langchain.com/docs/modules/chains/foundational/sequential_chains#sequential-chain

**Comment by davidmigloz** [comment]
Hey @ITP2023 , 

Thanks for the proposal! 

I've done a quick review and the logic seems fine. Would you like to create a pull request? I can add some suggestions once you issue it.

**Comment by ITP2023** [comment]
> Hey @ITP2023 ,
> 
> Thanks for the proposal!
> 
> I've done a quick review and the logic seems fine. Would you like to create a pull request? I can add some suggestions once you issue it.

@davidmigloz Sure
