### ISSUE TITLE
Add support for Gemini

### ISSUE THREAD

**Issue by quanshuli** [davidmigloz/langchain_dart#321]
### Feature request

hello, thanks very much for the package. can the support of [Gemini](https://ai.google.dev/tutorials/setup) be supported please. compared to `vertexAi`, it only requires an api key. 

### Motivation

`vertexAi` requires paid services to set up, while `gemini` currently has free tier, would be good to have support.

### Your contribution

here is a package: https://github.com/babakcode/flutter_gemini, but it does not support langchain pipeline.

**Comment by davidmigloz** [comment]
Hello @quanshuli ,

We already have support for Gemini, you can find it in the `langchain_google` package.

Check out the docs: https://langchaindart.com/#/modules/model_io/models/chat_models/integrations/googleai
