### ISSUE TITLE
Is there open ai Azure support for completions using this library?

### ISSUE THREAD

**Issue by dickverweij** [davidmigloz/langchain_dart#322]
### Feature request

I am trying to connect langchain to the azure version of open ai. It is just somewhat different then the normal openai chat-gpt4 api. 

completions api endpoint in azure openai

https://your_resource_name.openai.azure.com/openai/deployments/YOUR_DEPLOYMENT_NAME/completions?api-version=2023-05-15

completions api endpoint in regular openai

https://api.openai.com/v1/chat/completions

Is there support in langchain_dart for azure openai? 

### Motivation

We would like the langchart dart package to connect to our enterprise openai subscriptions.

### Your contribution

If nothing exists at the moment we are willing to submit a PR just for this problem.

**Comment by davidmigloz** [comment]
Hello @dickverweij ,

Yes, you should be able to connect to Azure OpenAI API with the current implementation.

Here you can find the docs:
- [`OpenAI`](https://pub.dev/documentation/langchain_openai/latest/langchain_openai/OpenAI-class.html#azure-openai-service) (for completions API)
- [`ChatOpenAI`](https://pub.dev/documentation/langchain_openai/latest/langchain_openai/ChatOpenAI-class.html#azure-openai-service) (for chat completions API)

Let me know if it works!
