### ISSUE TITLE
Add streaming support to `ChatGoogleGenerativeAI`

### ISSUE THREAD

**Issue by luisredondo** [davidmigloz/langchain_dart#325]
### Feature request

With the implementation of streamGenerateContent on #323, we could now add streaming support to the `ChatGoogleGenerativeAI` wrapper.

Some references:

- [Unsupported exception](https://github.com/davidmigloz/langchain_dart/blob/2cbd538a3b67ef6bdd9ab7b92bebc3c8c7a1bea1/packages/langchain_google/lib/src/chat_models/google_ai/chat_google_generative_ai.dart#L188-L193) in `ChatGoogleGenerativeAI`.
- How [it's done](https://github.com/davidmigloz/langchain_dart/blob/2cbd538a3b67ef6bdd9ab7b92bebc3c8c7a1bea1/packages/langchain_openai/lib/src/chat_models/chat_openai.dart#L253-L268) in `ChatOpenAI`

### Motivation

The completion of #299 

### Your contribution

I will submit a PR for this.

**Comment by luisredondo** [comment]
@davidmigloz I'm taking this one!

**Comment by davidmigloz** [comment]
Closing in favour of https://github.com/davidmigloz/langchain_dart/issues/332
