### ISSUE TITLE
Api does not respond in release mode

### ISSUE THREAD

**Issue by MunibullahShah** [davidmigloz/langchain_dart#326]
### System Info

Doctor summary (to see all details, run flutter doctor -v):
[√] Flutter (Channel stable, 3.16.9, on Microsoft Windows [Version 10.0.22621.3007], locale en-PK)
[√] Windows Version (Installed version of Windows is version 10 or higher)
[!] Android toolchain - develop for Android devices (Android SDK version 34.0.0)
    X cmdline-tools component is missing
      Run `path/to/sdkmanager --install "cmdline-tools;latest"`
      See https://developer.android.com/studio/command-line for more details.
    X Android license status unknown.
      Run `flutter doctor --android-licenses` to accept the SDK licenses.
      See https://flutter.dev/docs/get-started/install/windows#android-setup for more details.
[√] Chrome - develop for the web
[X] Visual Studio - develop Windows apps
    X Visual Studio not installed; this is necessary to develop Windows apps.
      Download at https://visualstudio.microsoft.com/downloads/.
      Please install the "Desktop development with C++" workload, including all of its default components
[√] Android Studio (version 2023.1)
[√] IntelliJ IDEA Ultimate Edition (version 2023.2)
[√] VS Code (version 1.86.0)
[√] Connected device (4 available)
[√] Network resources

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [X] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [X] retrievers
- [ ] agents

### Reproduction

1) call to createChatCompletion 
2) run in release mode

### Expected behavior

it should give the api response like in debug but it says
I/flutter (25807): Exception in getting response from gpt: OpenAIClientException({
I/flutter (25807):   "uri": "https://api.openai.com/v1/chat/completions",
I/flutter (25807):   "method": "POST",
I/flutter (25807):   "code": null,
I/flutter (25807):   "message": "Response error",
I/flutter (25807):   "body": "ClientException with SocketException: Failed host lookup: 'api.openai.com' (OS Error: No address associated with hostname, errno = 7), uri=https://api.openai.com/v1/chat/completions"
I/flutter (25807): })

**Comment by davidmigloz** [comment]
Hello @MunibullahShah ,

I've just tested it on my side and I can confirm that it's working properly.

The exception says:
```
ClientException with SocketException: Failed host lookup: 'api.openai.com' (OS Error: No address associated with hostname
```

That means that your system cannot resolve api.openai.com to an IP address. Verify that your internet connection is working properly and that there's nothing blocking the request.

Cheers.
