### ISSUE TITLE
Ollama Embeddings Documentation

### ISSUE THREAD

**Issue by agileWaterFail** [davidmigloz/langchain_dart#337]
### Issue with current documentation:

When possible I'd like to see some examples of using ollama embeddings in building up a chain, perhaps in a chatOllama. I'm attempting to give the llama2 a prompt with information to use for a chat I want to have with it, think role play and the information is backstory it needs that can't come from the user.

**Comment by davidmigloz** [comment]
Hello @agileWaterFail,

Thanks for your interest.

I've just added an example with an RAG pipeline using Ollama here:
https://langchaindart.com/#/modules/model_io/models/chat_models/integrations/ollama?id=rag-retrieval-augmented-generation-pipeline

Let me know if it's clear.

Cheers.

**Comment by agileWaterFail** [comment]
Thank you!
