### ISSUE TITLE
SocketException: Write failed (OS Error: Broken pipe, errno = 32)

### ISSUE THREAD

**Issue by lindeer** [davidmigloz/langchain_dart#340]
### System Info

langchain.dart: chromadb: 0.1.2
dart: 3.3.0
Platform: Linux-4.19.71-arm64
embedding model: bge-base-zh-v1.5-q4_k_m.gguf

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [X] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

error occured when I add embeddings to db:
```
Unhandled exception:
ChromaApiClientException({
  "uri": "http://0.0.0.0:8000/api/v1/collections/2363f552-1355-4e53-939d-ada7fc0c1ba6/add",
  "method": "POST",
  "code": null,
  "message": "Response error",
  "body": "ChromaApiClientException(ClientException with SocketException: Write failed (OS Error: Broken pipe, errno = 32), address = 0.0.0.0, port = 57766, uri=http://0.0.0.0:8000/api/v1/collections/2363f552-1355-4e53-939d-ada7fc0c1ba6/add)"
})
```
It happened when the request had a large body (mine is 52114 chars), the embedding model created two 768-size arrays. I changed to use `http.StreamedRequest` in  local `src/generated/client.dart`, but not worked and report the same error:
```
final req = http.StreamedRequest(method.name, uri);
req.sink.add(utf8.encode(bodyStr));
unawaited(req.sink.close());
request = req;
```
how to fix it?

### Expected behavior

successfully send a db request with large embeddings.

**Comment by lindeer** [comment]
something wrong with encoding?
When I query db with bare http of Dart, body of response is '{"ids":[["e92e5f30-19d2-1edc-98f0-2b84f4a33de4","e9319380-19d2-1edc-98f0-2b84f4a33de4"]],"distances":[[0.7655459642410278,0.9312208890914917]],"metadatas":[[{"source":"corpus/harry.txt"},{"source":"corpus/harry.txt"}]],"embeddings":null,"documents":[["å®¶ä½å¥³è´·ç', and use uft8 decode 'documents' once again, right answer came out.
Have no idea why...

**Comment by davidmigloz** [comment]
Hey @lindeer ,

Thanks for reporting!

I'm currently on holidays without my laptop. I'll debug it when I'm back.

**Comment by davidmigloz** [comment]
Hey @lindeer ,

Sorry for the delay. 
Have you managed to get it working?

I just ran [these tests](https://github.com/davidmigloz/langchain_dart/blob/main/packages/chromadb/test/chroma_client_test.dart) against Chroma v0.4.24 and I didn't see any issues. Could you add a test case that reproduces your issue?

**Comment by lindeer** [comment]
Hi @davidmigloz , I have to rewrite request from bare http package, and everything is OK now. I have no more details, but it may be not a common issue for others

**Comment by davidmigloz** [comment]
Interesting, I'll keep an eye on it. On which platform were you running it?

**Comment by lindeer** [comment]
Linux-4.19.71-arm64
