### ISSUE TITLE
support for ollama api keys

### ISSUE THREAD

**Issue by theoden8** [davidmigloz/langchain_dart#399]
### Feature request

Please, support api keys for ollama.

### Motivation

Ollama is not compatible with openai API, e.g. `/v1/models`. It is possible to hide ollama instance behind pre-determined api keys.

### Your contribution

I believe this is the part where this feature would be implemented: https://github.com/davidmigloz/langchain_dart/blob/main/packages/langchain_ollama/lib/src/chat_models/chat_ollama.dart#L148. The api key is passed as Bearer token in request header.

**Comment by davidmigloz** [comment]
Hello @theoden8,

You can provide any custom header using the`headers` field:

```dart
final chat = ChatOllama(
  baseUrl: 'https://your-base-url.com/api',
  headers: { 'api-key': 'YOUR_API_KEY' },
  defaultOptions: ChatOllamaOptions(
    model: 'llama3',
    temperature: 0,
  ),
);
```
