### ISSUE TITLE
Support streaming for LLMs and Chat models

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#4]
### OpenAI

> By default, when you request a completion from the OpenAI, the entire completion is generated before being sent back in a single response. If you're generating long completions, waiting for the response can take many seconds.
> 
> To get responses sooner, you can 'stream' the completion as it's being generated. This allows you to start printing or processing the beginning of the completion before the full completion is finished.
> 
> To stream completions, set stream=True when calling the chat completions or completions endpoints. This will return an object that streams back the response as data-only server-sent events. Extract chunks from the delta field rather than the message field.

- https://github.com/openai/openai-cookbook/blob/main/examples/How_to_stream_completions.ipynb
- https://python.langchain.com/en/latest/modules/models/llms/examples/streaming_llm.html

### VertexAI

- https://cloud.google.com/vertex-ai/docs/generative-ai/learn/streaming#text

**Comment by JacW93** [comment]
When can we expect this to be ready on langCahin?

**Comment by davidmigloz** [comment]
hey @JacW93 ,

Thanks for your interest.

I don't really like how streaming support is implemented on the original LangChain framework, so I'm evaluating some alternative implementations (concretely I like how [LiteChain](https://github.com/rogeriochaves/litechain) handles it).

I cannot guarantee when it'll be ready but it's high on the priorities list.

**Comment by JacW93** [comment]
Hey @davidmigloz! Thanks so much for your update. Sounds promising! What is the best way for me to get notified when it is ready?

**Comment by davidmigloz** [comment]
@JacW93 you can subscribe to this issue to receive updates 🙂

**Comment by briant-spindance** [comment]
As a stopgap measure, are there any plans to add callbacks? I'm working on a project with a potentially long longer of chains within a SequentialChain. Streaming would be idea, but at a minimum it would be nice to attach callbacks to track the progress through the sequence.

**Comment by davidmigloz** [comment]
hey @briant-spindance,

I have been busy for the last weeks implementing my own OpenAI API client ([openai_dart](https://pub.dev/packages/openai_dart)) which, among other things, improves streaming support compared to the previous client. Today I have completed the migration of LangChain.dart to the new client. And next on my table is to add streaming support using [LCEL](https://langchaindart.com/#/expression_language/interface) 🙂

Regarding callbacks, depending on your use case you may already be able to solve it using LCEL. You can always use a [RunnableFunction](https://langchaindart.com/#/expression_language/interface?id=runnablefunction) that calls your logger (or whatever you need) between two other runnables in a pipeline to inspect the output of the previous one.

Propper callback support would be nice to have but I cannot promise any timelines (contributions are welcomed).

**Comment by davidmigloz** [comment]
Happy to announce that streaming is now supported in [v0.0.15](https://github.com/davidmigloz/langchain_dart/releases/tag/langchain-v0.0.15).

- [Stream docs](https://langchaindart.com/#/expression_language/interface?id=stream)
- [OpenAI stream docs](https://langchaindart.com/#/modules/model_io/models/llms/integrations/openai?id=streaming)
- [ChatOpenAI stream docs](https://langchaindart.com/#/modules/model_io/models/chat_models/integrations/openai?id=streaming)
