### ISSUE TITLE
Migrate OpenAI Assistants API to v2

### ISSUE THREAD

**Issue by sherwinstar** [davidmigloz/langchain_dart#401]
### Feature request

Now the open_dart supports OpenAI-Beta: assistants=v1, Do you have plan to support OpenAI-Beta: assistants=v2? Thanks so much.

### Motivation

OpenAI assistant upgraded to OpenAI-Beta: assistants=v2 in April. There are some some api changes and some upgrades.

### Your contribution

Sorry, I am a fresh to OpenAI.

**Comment by davidmigloz** [comment]
Hello @sherwinstar ,

Thanks for creating the issue.

Yes, I have it on my TODO list, but I haven't found the time to do it yet. 
I'll try to do it this week, but cannot promise it.

**Comment by saulram** [comment]
@davidmigloz  not the creator of this issue, however I'm using your package to build something in Flutter using assistants API. it seems that there is a bug when using, the assistant tools "file_search" there is something that breaks, I'm trying to figure out what it is, but I have not worked with "freezed" yet, so.. in the mean time, just reporting it and attaching the error:

```
⛔ Error fetching data: CheckedFromJsonException
│ ⛔ Could not create `RunStepDeltaStepDetailsToolCalls`.
│ ⛔ There is a problem with "type".
│ ⛔ Invalid union type "file_search"!
```

**Comment by davidmigloz** [comment]
Thanks for reporting! I'll take a look later today. Do you have a sample code that reproduces the issue? That will help me 🙂

**Comment by davidmigloz** [comment]
Found [the issue](https://github.com/davidmigloz/langchain_dart/pull/404). It should be fixed in v0.3.1:
https://pub.dev/packages/openai_dart/changelog#031

**Comment by saulram** [comment]
Great work on this! @davidmigloz however after updated to v3.0.1 I'm still getting the same error.
I'm pasting here the code I'm running.
```dart
Future<void> fetchData() async {
    if (threadId.isEmpty) {
      log.e("Thread ID is empty");
      isLoading = false;
      notifyListeners();
      return;
    }

    try {
      final stream = client.createThreadRunStream(
        threadId: threadId,
        request: CreateRunRequest(
          assistantId: assistantId,
          additionalInstructions: "Update your memory before responding",
        ),
      );

      await for (var event in stream) {
        log.w("Event: $event");
        if (event.event == EventType.threadMessageCompleted ||
            event.event == EventType.threadMessageDelta) {
          handleEvent(event);
        } else {
          isLoading = text.isEmpty;
        }
        notifyListeners();
        if (event.event == EventType.threadMessageCompleted) break;
      }
    } catch (e) {
      log.e("Error fetching data: $e");
      text = "Error: $e";
      isLoading = false;
      notifyListeners();
    }
  }

  void handleEvent(AssistantStreamEvent event) {
    MessageObject message = event.data as MessageObject;
    text = message.content[0].text;
    isLoading = false;
  }
```
And the error shown in console is still:
```bash
┌───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
│ #0   packages/aspiral_flutter_client/features/alert_detail/viewmodels/alert_detail_screen_viewmodel.dart 74:7  fetchData
├┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄┄
│ ⛔ Error fetching data: CheckedFromJsonException
│ ⛔ Could not create `RunStepDeltaStepDetailsToolCalls`.
│ ⛔ There is a problem with "type".
│ ⛔ Invalid union type "file_search"!
└───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

```
I ran a `flutter clean`and then re build the app, but still failing.

**Comment by davidmigloz** [comment]
oh hmm, thanks for trying it out. I'll dig deeper later today (thanks for the sample code).

**Comment by davidmigloz** [comment]
Found the issue. Should be fixed by https://github.com/davidmigloz/langchain_dart/pull/412
