### ISSUE TITLE
OpenAI createVectorStore throw an exception

### ISSUE THREAD

**Issue by Paroca72** [davidmigloz/langchain_dart#409]
### System Info

OpenAI, Flutter

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

Ia allowed to pass CreateVectorStoreRequest empty but if you pass empty will throw and exception:

```
VectorStoreObject vectorStore = await client!.createVectorStore(
        request: const CreateVectorStoreRequest(),
);
```
type 'Null' is not a subtype of type 'String' in type cast

Thanks

### Expected behavior

No exception

**Comment by davidmigloz** [comment]
Thanks for the report, I'll look into it.

**Comment by davidmigloz** [comment]
It seems you created a vector store with `null` name, while the client expects a vector store to have a name. I'll make name nullable.
