### ISSUE TITLE
OpenAI listVectorStoreFiles throw an error if the list is empty

### ISSUE THREAD

**Issue by Paroca72** [davidmigloz/langchain_dart#410]
### System Info

Flutter, Dart

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

The request throw an error if the list is empty

```
ListVectorStoreFilesResponse files =
          await client!.listVectorStoreFiles(vectorStoreId: id, limit: 100);
```

type 'Null' is not a subtype of type 'String' in type cast

### Expected behavior

The list of files

**Comment by davidmigloz** [comment]
Thanks for reporting. It seems you created a vector store with `null` name, while the client expects a vector store to have a name. I'll make name nullable.

**Comment by Paroca72** [comment]
Hello,

Thanks for the patch but referring to the API the name should be optional..
https://platform.openai.com/docs/api-reference/vector-stores/create

Thanks

**Comment by davidmigloz** [comment]
Their API spec is not consistent. It's optional in the create vector store request, but not optional in the vector store object:
https://platform.openai.com/docs/api-reference/vector-stores/object

Anyway, I've made the name nullable in the latest release. So you should not get the exception anymore:
https://pub.dev/packages/openai_dart/changelog#032
