### ISSUE TITLE
Getting 400 error when chat with images

### ISSUE THREAD

**Issue by guchengxi1994** [davidmigloz/langchain_dart#447]
### System Info

langchain-dart: 0.7.1

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [X] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

I used dart and python codes with `OpenAI` to chat with images, python codes worked well, but dart codes raised exceptions like this.

![image](https://github.com/davidmigloz/langchain_dart/assets/33513462/93c5fc67-aa62-4c9f-8e40-b835bc184428)

here is python codes.

```python
from openai import OpenAI
import os

def get_response():
    client = OpenAI(
        api_key="sk-******",  
        base_url="https://dashscope.aliyuncs.com/compatible-mode/v1",   # openai api should works too
    )
    completion = client.chat.completions.create(
        model="qwen-vl-plus",
        messages= [
            {
              "role": "user",
              "content": [
                {
                  "type": "text",
                  "text": "what is this"
                },
                {
                  "type": "image_url",
                  "image_url": {
                    "url": "https://dashscope.oss-cn-beijing.aliyuncs.com/images/dog_and_girl.jpeg",
                    "detail":"auto"
                  }
                }
              ]
            }
          ],
        top_p=0.8,
        stream=True
)
    for chunk in completion:
        print(chunk.model_dump_json())

if __name__ == '__main__':
    get_response()

```

here is dart codes.

```dart
final llm = ChatOpenAI(
    apiKey: "sk-******",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    defaultOptions: ChatOpenAIOptions(
      model: "qwen-vl-plus",
    ),
  );
  final prompt = PromptValue.chat([
    ChatMessage.human(
      ChatMessageContent.multiModal([
        ChatMessageContent.text('What is this?'),
        ChatMessageContent.image(
          data:
              "https://dashscope.oss-cn-beijing.aliyuncs.com/images/dog_and_girl.jpeg",
        ),
      ]),
    ),
  ]);

  for (final i in prompt.toChatMessages()) {
    print(i);
  }

  final res = await llm.invoke(prompt);

  print(res.outputAsString);

```

![image](https://github.com/davidmigloz/langchain_dart/assets/33513462/78bf1e3b-877c-4267-8466-72f563275853)
 
after converting `content: json['content'] as String?` to  `content: "${json['content']}"`, codes are ok.

### Expected behavior

not sure why this exception happens.

**Comment by davidmigloz** [comment]
It seems the provider you are using doesn't comply with the OpenAI API.
The `content` field can only be of type `String`, not a type `List` as you seem to be getting ([ref](https://github.com/openai/openai-openapi/blob/14b66f5de2816a059bab85bf0dde69166d696adc/openapi.yaml#L7727-L7730)).

Here we have a test testing a prompt with images and it is working fine with the official OpenAI API:
https://github.com/davidmigloz/langchain_dart/blob/c5c15a105f0fb55fcff41d0ec1a39badb3cc7e58/packages/langchain_openai/test/chat_models/chat_openai_test.dart#L385-L409

**Comment by guchengxi1994** [comment]
seems like it is a issue releated to qwen, I will close this issue. Thanks for help.
