### ISSUE TITLE
Improve Retrieval documentation 

### ISSUE THREAD

**Issue by ScottS2017** [davidmigloz/langchain_dart#465]
### System Info

In the Retrieval tutorial [here](https://langchaindart.dev/#/expression_language/cookbook/retrieval), in the first code block it says:

`final vectorStore = Chroma(embeddings: embeddings);`

Error: _"The method 'Chroma' isn't defined..."_

Solution: Change _Chroma_ to _MemoryVectorStore_.

I would just put in a PR but it's a website issue, not a package issue.

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [X] retrievers
- [ ] agents

### Reproduction

Follow the instructions in the tutorial at https://langchaindart.dev/#/expression_language/cookbook/retrieval

### Expected behavior

No error saying the method (actually class) doesn't exist.

**Comment by davidmigloz** [comment]
Hey @ScottS2017 ,

Nice to see you here 🙂

[`Chroma`](https://www.trychroma.com/) is actually one of the vector stores we support. It's part of the [`langchain_chroma`](https://pub.dev/packages/langchain_chroma) package (I'll update the tutorial to mention that you need to add the `langchain_chroma` package).

The `MemoryVectorStore` is mainly for prototyping, as it keeps all the vectors in memory and brute-forces similarity. If you want to use a more scalable embedded vector store, I recommend you check the [ObjectBox integration](https://langchaindart.dev/#/modules/retrieval/vector_stores/integrations/objectbox).

(it's on my TODO list to create a better overview of all the integrations we currently support and in which package they are...)

**Comment by davidmigloz** [comment]
By the way, the langchaindart.dev documentation is also in this repo, in case you want to send some PR in the future:
- https://github.com/davidmigloz/langchain_dart/tree/main/docs

**Comment by ScottS2017** [comment]
A quick workaround might be something like this at the start of every tutorial section page. It will tell users that they may find what they need in other packages, instead of having them think the classes they need were simply deprecated and deleted:

// NOTE: Many things in langchain_dart are changing quickly. If your IDE shows an error and asks you to make a class for the error, try some of the langchain_dart packages on pub. EG: Loaders are now in the langchain_community package. There are several others, a few of them are:
// langchain
// langchain_core
// langchain_chroma
// langchain_community
// langchain_google
// langchain_mistralai
// langchain_ollama
// langchain_openai

**Comment by davidmigloz** [comment]
Closing this issue in favour of 
https://github.com/davidmigloz/langchain_dart/issues/466
