### ISSUE TITLE
Unable to set URI or port for Chroma( )

### ISSUE THREAD

**Issue by ScottS2017** [davidmigloz/langchain_dart#471]
### Feature request

There are many cases in which people are running ChromaDB somewhere other than localhost 8000, especially if 8000 is already taken by other things. I, for one, run my databases on a different machine in my LAN and change the port from 8000. Currently, the constructor looks like this:

```
Chroma({
    this.collectionName = 'langchain',
    this.collectionMetadata,
    required super.embeddings,
    final String tenant = 'default_tenant',
    final String database = 'default_database',
    final String baseUrl = 'http://localhost:8000',
    final Map<String, String> headers = const {},
    final http.Client? client,
  }) : _client = ChromaClient(
          tenant: tenant,
          database: database,
          baseUrl: baseUrl,
          headers: headers,
          client: client,
        );
```
        
In order to allow the dev to set the URI and port, what we need is this:

```
CustomChroma({
    this.collectionName = 'langchain',
    this.collectionMetadata,
    this.baseUrl  = 'http://localhost:8000',
    required super.embeddings,
    final String tenant = 'default_tenant',
    final String database = 'default_database',
    final Map<String, String> headers = const {},
    final http.Client? client,
  }) : _client = ChromaClient(
    tenant: tenant,
    database: database,
    baseUrl: baseUrl,
    headers: headers,
    client: client,
  );

  /// Optional base URI.
  String baseUrl;
```

### Motivation

I need to assign the db URI and port to something other than localhost:8000

### Your contribution

Forking and submitting a PR.

**Comment by ScottS2017** [comment]
Needs to be posted in langchain_chroma

**Comment by ScottS2017** [comment]
PR #472 submitted to resolve this issue.

**Comment by davidmigloz** [comment]
Hello @ScottS2017,

That functionality is already supported by the current constructor.

```dart
final vectorStore = Chroma(
  embeddings: OpenAIEmbeddings(apiKey: openaiApiKey),
  baseUrl: 'http://localhost:8888',
);
```

It is also explained in [the documentation](https://langchaindart.dev/#/modules/retrieval/vector_stores/integrations/chroma?id=using-docker):
<img width="854" alt="image" src="https://github.com/davidmigloz/langchain_dart/assets/6546265/76449534-2072-4979-8bbd-4eb78a2733fc">

Isn't this what you need?

**Comment by davidmigloz** [comment]
I'll close the issue and the PR as this functionality is already supported. 
If you are missing something with the current API, please feel free to reopen the issue.
