### ISSUE TITLE
Invalid paramenters for ChatOllama

### ISSUE THREAD

**Issue by WilliamKarolDiCioccio** [davidmigloz/langchain_dart#478]
### System Info

Platform: Window 11
GPU: RTX 4060 8GB
langchain: ^0.7.1
langchain_ollama: ^0.2.1+1

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [X] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

The errors occur when setting f16 key/value to false:

```json
{
  "uri": "http://localhost:11434/api/chat",
  "method": "POST",
  "code": 500,
  "message": "Unsuccessful response",
  "body": {
  "error": "llama runner process has terminated: exit status 1 error: unknown argument: --memory-f32"
}
```

And non uniform memory access (NUMA) to true:

```json
{
  "uri": "http://localhost:11434/api/chat",
  "method": "POST",
  "code": 500,
  "message": "Unsuccessful response",
  "body": {
  "error": "llama runner process has terminated: exit status 1 error:invalid parameter for argument: --numa"
}
```

I'm reporting this here as I'm not an Ollama expert and I'm not sure if that's a LangChain related error or not

### Expected behavior

Enable and disable the intended settings without any errors

**Comment by davidmigloz** [comment]
Hey @WilliamKarolDiCioccio,

I've double checked our Ollama API client and it seems to match what the Ollama API expects.

You can check the parameters Ollama supports here:
- https://github.com/ollama/ollama/blob/4d71c559b21ec9207a328b824ce534bdbaf59f2d/api/types.go#L137-L174

And their default values here:
- https://github.com/ollama/ollama/blob/4d71c559b21ec9207a328b824ce534bdbaf59f2d/api/types.go#L484-L519
- `numa` is `false` by default
- `f16_kv` is `true` by default

So it may be an issue on Ollama side.

Regarding your [app implementation](https://github.com/WilliamKarolDiCioccio/open_local_ui/blob/cd88e3c7ce87242babf56d365ff13c23546d54b8/app/lib/backend/providers/chat.dart#L614-L650) (nice app btw 🙂), I would not hardcode the defaults on your end. If the user doesn't provide a value, just set the parameter to `null`. That way it will use the default value from Ollama (which can change from time to time).

**Comment by WilliamKarolDiCioccio** [comment]
Thank @davidmigloz you so much for the quick feedback, the compliments and the suggestion not to hardcode the defaults 😄 (I'll change that)

**Comment by davidmigloz** [comment]
You're welcome 🙂

Yes, we can close this issue as there's nothing else we can do on our side.

I've fixed the default values given in the API documentation for a couple of parameters that were incorrect (https://github.com/davidmigloz/langchain_dart/pull/479). So the review wasn't for nothing 😄

Cheers.
