### ISSUE TITLE
ChatOllama keepAlive is ignored if set in the default options 

### ISSUE THREAD

**Issue by WilliamKarolDiCioccio** [davidmigloz/langchain_dart#480]
### System Info

Platform: Windows 11
GPU: RTX 4060 8GB
langchain: ^0.7.3
langchain_ollama: ^0.2.2+1

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [x] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

As you can see [here](https://github.com/WilliamKarolDiCioccio/open_local_ui/blob/2fc0628756cf50785eb5bc74c1b8e9c6c755bce4/app/lib/backend/providers/chat.dart#L654) I'm simply setting the keepalive time to the model specific one if it is specified otherwise to the global one (yeah, its the same piece of code from last time). I double checked the values in debug mode and those are correct. However by looking at the GPU's memory usage I see that the model is being unloaded after the default five minutes (checked with stopwatch), this is confirmed by the response latency after this short period as it loads the model again. 

### Expected behavior

We don't need to add anything on the expected behavior \_(o_o)_/.

**Comment by davidmigloz** [comment]
hello @WilliamKarolDiCioccio,

I've just tested it and seems to be working fine. You can check whether a model is still loaded using the `ollama ps` command.

- If I set `keepAlive: 0` and  run `ollama ps` after invoking the model, I get an empty list
- If I set `keepAlive: 1` and run `ollama ps` after invoking the model, I get the model I run. After 1min, I get an empty list
- If I set `keepAlive: 1`, the model is always listed when running `ollama ps`

Make sure you're using the latest version of Ollama, just in case. 

Cheers.

**Comment by WilliamKarolDiCioccio** [comment]
I'll check it using the ps command, however considering the response latency I think it is being unloaded so the only remaining solution is to update Ollama. Tomorrow I'll check and let you know

The famous phrase: "It doesn't work, on my machine"

**Comment by davidmigloz** [comment]
> The famous phrase: "It doesn't work, on my machine"

Always the case 😄

Let me know if after upgrading the issue is solved. In the [latest version](https://github.com/ollama/ollama/releases/tag/v0.2.0), they reworked their memory management substantially as now they support parallel requests and loading different models at the same time.

**Comment by davidmigloz** [comment]
Hmm could it be that the options are being overridden somewhere else? Let me know the branch from you're repo where you're working, I can give it a try 🙂

**Comment by WilliamKarolDiCioccio** [comment]
Don't worry, I don't want to waste your time. I'll check it myself. If the problem is what you're saying it should be pretty easy to identify. If won't find it then you'll be welcome to have a look, in such case you can have a look directly to the main branch.

**Comment by WilliamKarolDiCioccio** [comment]
![Screenshot 2024-07-09 215315](https://github.com/davidmigloz/langchain_dart/assets/88447902/5479ed8d-8cf6-4190-bb79-e5137ba3aec6)

Nope.

As you can see from the local variables in debugging mode the options are still showing the correct value, moreover I took this screen on toggling a breakpoint in the [`_buildChain()`](https://github.com/WilliamKarolDiCioccio/open_local_ui/blob/9df535a9eff0062c3c3158970a72d7da0fc5d5d5/app/lib/backend/providers/chat.dart#L347) method so this is the final values used for generation.

**Comment by davidmigloz** [comment]
Hey @WilliamKarolDiCioccio ,

My bad, it is actually a bug in LangChain.dart. While reviewing #483 I found out that `keepAlive` is only considered if it's passed in the invoke options, while it's ignored if it's set in the default options:

https://github.com/davidmigloz/langchain_dart/blob/4bb79c30002aec3e673828ef2762e853491ea594/packages/langchain_ollama/lib/src/chat_models/chat_ollama.dart#L222

When tested it I was passing it in the invoke options, that's why I wasn't able to reproduce the issue.

I'll issue a fit later today.

**Comment by Ganeshsivakumar** [comment]
Hi @davidmigloz 

Then is guess, it should take keepAlive value from whichever is provided, either from defaultOptions or invoke options.

**Comment by davidmigloz** [comment]
Yes, it should use the `defaultOptions` value if `options` is `null`.

So from:
```dart
keepAlive: options?.keepAlive
```

to:
```dart
keepAlive: options?.keepAlive ?? defaultOptions.keepAlive,
```

I've fixed it in my commit at https://github.com/davidmigloz/langchain_dart/pull/483
