### ISSUE TITLE
Code Assist AI trained on repo

### ISSUE THREAD

**Issue by samyakkkk** [davidmigloz/langchain_dart#490]
### Idea or request for content:

Dear maintainers, greetings from [CommandDash](https://commanddash.io)! 

We are a tool to turn docs and examples of your library into a code generation AI agent which **helps devs directly generate code for your library as per their requirements.**

Our team came across Langchain Dart and figured it could be helpful for new developers building on it to have one such agent. It's ready and is accessible on: [Web](https://app.commanddash.io/agent?github=https://github.com/davidmigloz/langchain_dart) (Try here!) | [VSCode Extension](https://marketplace.visualstudio.com/items?itemName=WelltestedAI.fluttergpt) 

You can link this in your readme as a badge:

<a href="https://app.commanddash.io/agent?github=https://github.com/davidmigloz/langchain_dart"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA?style=for-the-badge"></a>
```md
<a href="https://app.commanddash.io/agent?github=https://github.com/davidmigloz/langchain_dart"><img src="https://img.shields.io/badge/AI-Code%20Assist-EB9FDA"></a>
```
Please feel free to mention it if you believe this could be helpful for new users. Or, close the issue if not. 🙏🏻

_The agent is free to use, fully safe (no data retained) and auto-refreshes to stay upto date._

Best wishes!

**Comment by vshanbha** [comment]
@davidmigloz 
It seems that the Commanddash.io site is no longer live and likely pointing now to some malicious links. 
Please can you check and remove that link from the documentation if it is no longer valid.

**Comment by samyakkkk** [comment]
Hi @davidmigloz, yes we had to shut shops, we can remove the site from docs :)
