### ISSUE TITLE
CORS error with openrouter

### ISSUE THREAD

**Issue by richardchui** [davidmigloz/langchain_dart#510]
Using openrouter will encounter a CORS issue.  No problem with other services such as TogetherAI and Groq.

Have tried using openrouter with another dart package (dart_openai) and everything works fine.

**Comment by davidmigloz** [comment]
Hey @richardchui,

OpenRouter doesn't allow the `OpenAI-Beta` header in its CORS configuration. The `OpenAIClient` sets this header by default to enable the assistants API which is still in beta. You can remove this header by settings `beta: null`:

```dart
final client = OpenAIClient(
  apiKey: Platform.environment['OPENAI_API_KEY'],
  beta: null,
);
```

**Comment by richardchui** [comment]
Problem sovled.  Cannot thank you enough for this.
