### ISSUE TITLE
Add support for ConversationalRetrievalChain

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#52]

**Comment by mdshihabuddinroky** [comment]
Please add this as soon as possible

**Comment by mdshihabuddinroky** [comment]
> @mdshihabuddinroky the project is open to contributors 🙂

I haven't enough knowledge. If you can That would be helpful. thank you soo much for your contribution

**Comment by davidmigloz** [comment]
Not planning to implement this anymore, as it can be easily recreated using LCEL
