### ISSUE TITLE
How to have continous chat with the ai?

### ISSUE THREAD

**Issue by danieljiwonkang98** [davidmigloz/langchain_dart#528]
### Issue with current documentation:

No documentation on how to have continous chat with the ai knowing previous context?

**Comment by davidmigloz** [comment]
Hello @danieljiwonkang98 ,

You can use some of the [memory classes](https://github.com/davidmigloz/langchain_dart/tree/main/packages/langchain/lib/src/memory) that LangChain.dart provides, or you can manage the history yourself.

Here you have an example of adding memory to a chain:
https://langchaindart.dev/#/expression_language/cookbook/adding_memory

In this other example, the history is handed manually:
https://github.com/davidmigloz/langchain_dart/discussions/519#discussioncomment-10298964

Hope that helps!
