### ISSUE TITLE
How to implement Azure Open AI to LangChain.dart?

### ISSUE THREAD

**Issue by Percival-Chan** [davidmigloz/langchain_dart#529]
### Issue with current documentation:

I would prefer using Azure OpenAi service to call a langchain agent. How can I implement the setup to do so?
Here is the part I struggled with the parameter:

_chatModel = ChatOpenAI(
      apiKey: myKey,
      organization: "azure",
      baseUrl: muUrl,
      defaultOptions: const ChatOpenAIOptions(model: "gpt-4o", temperature: 0,),
      queryParams: 
    );

It would be great if any example or tutorial would be kindly provided to implement Azure Open Ai.

![Screenshot from 2024-08-20 15-48-20](https://github.com/user-attachments/assets/fb049f1c-8f1f-4941-9287-83a477ec5405)

**Comment by davidmigloz** [comment]
Hey @Percival-Chan ,

In the API docs you can find how to configure `ChatOpenAI` with Azure:
https://pub.dev/documentation/langchain_openai/latest/langchain_openai/ChatOpenAI-class.html#azure-openai-service

Let me know if that works.

**Comment by Percival-Chan** [comment]
> Hey @Percival-Chan ,
> 
> In the API docs you can find how to configure `ChatOpenAI` with Azure: https://pub.dev/documentation/langchain_openai/latest/langchain_openai/ChatOpenAI-class.html#azure-openai-service
> 
> Let me know if that works.

It works, thankyou so much, look forward for the langgraph updates!! Cheers.

**Comment by davidmigloz** [comment]
Great to hear!
