### ISSUE TITLE
Add support for VectorStoreRetrieverMemory

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#54]
https://python.langchain.com/docs/modules/memory/how_to/vectorstore_retriever_memory

**Comment by davidmigloz** [comment]
@dileep9490 here you have some resources that should help you to implement it:

- [Docs](https://python.langchain.com/docs/modules/memory/how_to/vectorstore_retriever_memory)
- [Python code](https://github.com/hwchase17/langchain/blob/master/langchain/memory/vectorstore.py)
- [TypeScript code](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/memory/vector_store.ts)
- [TypeScript tests](https://github.com/hwchase17/langchainjs/blob/main/langchain/src/memory/tests/vector_store_memory.int.test.ts)

Dependencies:
- `VectorStoreRetriever` (already implemented)
- `BaseMemory`(already implemented) 

Sample code that we should be able to run when it's implemented:

```dart
final embeddings = OpenAIEmbeddings(apiKey: openaiApiKey);
final vectorStore = MemoryVectorStore(embeddings: embeddings);

final memory = VectorStoreRetrieverMemory(retriever: vectorStore.asRetriever());

memory.saveContext(
  inputValues: {
    'foo': 'bar2',
    'bar': 'foo2',
  },
  outputValues: {
    'foo': 'bar',
  },
);

final memories = await memory.loadMemoryVariables();
print(memories);
```

**Comment by dileep9490** [comment]
@davidmigloz can you assign me this issue

**Comment by dileep9490** [comment]
@davidmigloz how can i get the test data? the type script tests are using TensorFlow embeddings

**Comment by davidmigloz** [comment]
You can use `OpenAIEmbeddings` instead that it's already implemented.

**Comment by dileep9490** [comment]
@davidmigloz that requires my OpenAI API key right if so i'm having some issues with it? or is there any data available?

**Comment by davidmigloz** [comment]
yes, it requires your OpenAI API key.

To add data to the `VectorStoreRetrieverMemory` you have to call the `saveContext` method (you can check [the example](https://github.com/davidmigloz/langchain_dart/issues/54#issuecomment-1627029977) from the previous comment).

Then when you call `memory.loadMemoryVariables(values)` it should return the relevant Documents from the vector store.

Another option if you don't want to use OpenAI API is to use a local embedding model using https://www.premai.io/#PremApp. You can still use `OpenAIEmbeddings` wrapper, but specifying `client=OpenAIClient.local('http://localhost:8000')` (replace 8000 with the port where your PremApp is running the model).
