### ISSUE TITLE
OpenAI Realtime API

### ISSUE THREAD

**Issue by Jonovono** [davidmigloz/langchain_dart#561]
### Feature request

I see this package: https://pub.dev/packages/openai_realtime_dart/versions but doesn't seem like it exists?

### Motivation

Would be awesome, but obviously no rush as it just came out

### Your contribution

I am willing to test it out, feedback, etc

**Comment by davidmigloz** [comment]
Hey @Jonovono,

I'm working on it 🙂
I have a first working implementation that I'm planning to release in the following days.

I'll let you know when it's live.

**Comment by davidmigloz** [comment]
@Jonovono I've released v0.0.1:
- https://pub.dev/packages/openai_realtime_dart
- https://github.com/davidmigloz/langchain_dart/tree/openai_realtime_dart-v0.0.1/packages/openai_realtime_dart

It follows the same structure as the [official reference client](https://github.com/openai/openai-realtime-api-beta). Currently, it doesn't have types. I'm waiting for OpenAI to release the spec to generate the types automatically.
