### ISSUE TITLE
Error: The argument type 'Namespace' can't be assigned to the     parameter type 'String?'

### ISSUE THREAD

**Issue by zaksnet** [davidmigloz/langchain_dart#565]
### System Info

I'm getting the following error with LangChain v 0.7.7:
```CMD
/..../AppData/Local/Pub/Cache/hosted/pub.dev/langchain-0.7.7/lib/src/embeddin
gs/cache.dart:138:30: Error: The argument type 'Namespace' can't be assigned to the    
parameter type 'String?'.
 - 'Namespace' is from 'package:uuid/enums.dart'
 ('/C:/Users/zaksc/AppData/Local/Pub/Cache/hosted/pub.dev/uuid-4.5.1/lib/enums.dart'). 
    return uuid.v5(Namespace.URL, keyHash);
                             ^
```

It works with v0.7.6. Related to https://github.com/davidmigloz/langchain_dart/pull/558/commits/518e063b94aa2f74063e175a6709ed0f89b2936f.
I tested this with:
```Dart
 String encodeKey(final String key) {
    final keyHash = sha1.convert(utf8.encode(key)).toString();
    return uuid.v5(Namespace.url.toString(), keyHash);
  }
```
And it works but i'm not sure if this is the right fix in this case so i'm not making a PR.

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

Upgarde langchain to 0.7.7

### Expected behavior

No errors

**Comment by davidmigloz** [comment]
Released:
https://github.com/davidmigloz/langchain_dart/blob/main/CHANGELOG.md#langchain---v0771
