### ISSUE TITLE
Add support for OpenAITaggingChain

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#57]
https://python.langchain.com/docs/modules/chains/additional/tagging

**Comment by mirkancal** [comment]
This url doesn't exists anymore but probably it was just structured output?

```
llm = ChatOpenAI(temperature=0, model="gpt").with_structured_output(
    Classification
)

tagging_chain = tagging_prompt | llm
```

**Comment by davidmigloz** [comment]
When this issue was created structured outputs and even json mode weren't a thing yet 😄
I'll close this issue as it can now easily be done with structured outputs as you mention.
