### ISSUE TITLE
Update to message role in createThreadMessage() for OpenAI Dart package

### ISSUE THREAD

**Issue by CalebMowery** [davidmigloz/langchain_dart#575]
### Issue with current documentation:

In the documentation, creating a message currently has a constructor for creating a role when creating a thread message:

> Create message:
> 
> final res = await client.createThreadMessage(
>   threadId: threadId,
>   request: CreateMessageRequest(
>     role: CreateMessageRequestRole.user,
>     content: CreateMessageRequestContent.text(
>       'I need to solve the equation `3x + 11 = 14`. Can you help me?',
>     ),
>   ),
> );

### Idea or request for content:

After reviewing the package code, I believe it needs to be updated to read 'MessageRole.user' which worked for me!

**Comment by davidmigloz** [comment]
Thanks for pointing it out. I've fixed the documentation in https://github.com/davidmigloz/langchain_dart/pull/579.
