### ISSUE TITLE
Hope to support running local models

### ISSUE THREAD

**Issue by xcc3641** [davidmigloz/langchain_dart#589]
### Feature request

Hi,

It would be nice to have support for the ability to run local models for dart/flutter, like  [llam.rn](https://github.com/mybigday/llama.rn).

### Motivation

There are many local models that can run on mobile devices now. I think if we can support this feature, it will greatly help more users experience offline AI capabilities.

### Your contribution

I'm not very familiar with C++, but I'll do my best if needed.

**Comment by davidmigloz** [comment]
Hey @xcc3641,

Thanks for bringing up this topic.

Currently we only support running local models via Ollama (on desktop).

For mobile, we have several open issues:
- https://github.com/davidmigloz/langchain_dart/issues/432
- https://github.com/davidmigloz/langchain_dart/issues/317
- https://github.com/davidmigloz/langchain_dart/issues/361

I'll close this issue in favour of those.
