### ISSUE TITLE
Could not create `ResponseStatusDetails`.

### ISSUE THREAD

**Issue by andreiavornic** [davidmigloz/langchain_dart#595]
### System Info

ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: CheckedFromJsonException
Could not create `ResponseStatusDetails`.
There is a problem with "type".
Invalid union type "cancelled"!
#0      _$ResponseStatusDetailsFromJson (package:openai_realtime_dart/src/schema/generated/schema/schema.freezed.dart:11526:7)
#1      new ResponseStatusDetails.fromJson (package:openai_realtime_dart/src/schema/generated/schema/response_status_details.dart:52:7)
#2      _$$ResponseImplFromJson (package:openai_realtime_dart/src/schema/generated/schema/schema.g.dart:139:35)
#3      new _$ResponseImpl.fromJson (package:openai_realtime_dart/src/schema/generated/schema/schema.freezed.dart:1370:7)
#4      _$ResponseFromJson (package:openai_realtime_dart/src/schema/generated/schema/schema.freezed.dart:1150:20)
#5      new Response.fromJson (package:openai_realtime_dart/src/schema/generated/schema/response.dart:41:7)
#6      _$$RealtimeEventResponseDoneImplFromJson (package:openai_realtime_dart/src/schema/generated/schema/schema.g.dart:1803:26)
#7      new _$RealtimeEventResponseDoneImpl.fromJson (package:openai_realtime_dart/src/schema/generated/schema/schema.freezed.dart:45795:7)

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

after RealtimeEventType.conversationInterrupted

### Expected behavior

No errors

**Comment by davidmigloz** [comment]
Hey @andreiavornic ,

Are you using the latest version ([v0.0.3](https://pub.dev/packages/openai_realtime_dart/changelog#003))?

As far as I can see the current code handles `cancelled` already:

https://github.com/davidmigloz/langchain_dart/blob/d2723976c3f0c36c95115b4b756492e223ffe812/packages/openai_realtime_dart/lib/src/schema/generated/schema/response_status_details.dart#L22-L36

**Comment by davidmigloz** [comment]
I'll close this issue for now, please feel free to reopen it if you can still reproduce it with the latest version.
