### ISSUE TITLE
Missing bearer or basic authentication in header, param: null, eventId: null

### ISSUE THREAD

**Issue by ronnnald** [davidmigloz/langchain_dart#599]
### System Info

When I was trying to use openai_realtime_dart: ^0.0.3 with following codes, it appears Connected to "wss://api.openai.com/v1/realtime" yet when trying to receive the response after submitting request, i got this error:
flutter: RealtimeEvent.error(eventId: event_AT79LFUhCzb6peAlJDhME, type: RealtimeEventType.error, error: APIError(type: invalid_request_error, code: null, message: Missing bearer or basic authentication in header, param: null, eventId: null))

Was trying to use web_socket_channel 3.0.1 with headers and it worked.

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

```dart
Future<void> StreamingAI() async {
  final client = RealtimeClient(
    apiKey: Platform.environment[OPENAPIKEY],
  );

  await client.updateSession(instructions: 'You are a great, upbeat friend.');
  await client.updateSession(voice: Voice.alloy);
  await client.updateSession(
    turnDetection: null,
    inputAudioTranscription:
        const InputAudioTranscriptionConfig(model: 'whisper-1'),
  );

  client.on(RealtimeEventType.all, (e) {
    print(e);
  });

  client.on(RealtimeEventType.conversationUpdated, (e) {
    final event = e as RealtimeEventConversationUpdated;
    print(event);
    final item = event.result.item;
    final delta = event.result.delta;
  });

  await client.connect();

  await client.sendUserMessageContent(const [
    ContentPart.text(text: 'Can you tell me the temperature of New York'),
  ]);
  await client.sendUserMessageContent(const [
    ContentPart.text(text: 'Thank you and how are you doing today?'),
  ]);
}
```

### Expected behavior

Successful websocket connection and able to receive valid response

**Comment by davidmigloz** [comment]
hey @ronnnald,

Thanks for the report, I'll have a look at it soon.

**Comment by davidmigloz** [comment]
Hey @ronnnald,

I've just tried your sample code, and it worked fine for me. I didn't get any authentication error.
I would double-check that your `OPENAPIKEY` env variable contains a valid token. 

I'll close this issue for now, if you still think is a bug please feel free to provide more details.
