### ISSUE TITLE
Resource not found - 404 error when Im using createThread

### ISSUE THREAD

**Issue by MohammadSharafi** [davidmigloz/langchain_dart#606]
### System Info

openai_dart: ^0.4.4
dart

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [X] prompts
- [X] llms
- [ ] chat-models
- [ ] output-parsers
- [ ] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction

here it is my code :

```
   client = OpenAIClient(
      baseUrl: 'https://******.openai.azure.com/openai/deployments/gpt-4o',
      headers: {'api-key': '*********************************'},
      queryParams: {'api-version': '2024-08-01-preview'},
    );
    
```
    
    
```
      var res = await client?.createThread(
        request: CreateThreadRequest(
        ),
      );
```
      
      
after calling this i getting below error
      
      
Unhandled Exception: OpenAIClientException

```
{
  "uri": "https://*****.openai.azure.com/openai/deployments/gpt-4o/threads",
  "method": "POST",
  "code": 404,
  "message": "Unsuccessful response",
  "body": {
    "error": {
      "code": "404",
      "message": "Resource not found"
    }
  }
}

```

    
    
    
    
    

### Expected behavior

my goal is create thread and use thread id

**Comment by MohammadSharafi** [comment]
@davidmigloz could you please check this?

**Comment by davidmigloz** [comment]
Hey @MohammadSharafi ,

The endpoint called looks correct:
https://learn.microsoft.com/en-us/azure/ai-services/openai/assistants-reference-threads

Are you sure your "deployment" is correctly configured?

**Comment by davidmigloz** [comment]
Hey @MohammadSharafi ,

According to the docs, the URL should be like:
```
POST https://YOUR_RESOURCE_NAME.openai.azure.com/openai/threads?api-version=2024-08-01-preview
```

Can you try removing `/deployments/gpt-4o` from your baseUrl?
```
client = OpenAIClient(
      baseUrl: 'https://******.openai.azure.com/openai',
      headers: {'api-key': '*********************************'},
      queryParams: {'api-version': '2024-08-01-preview'},
);
```

**Comment by MohammadSharafi** [comment]
https://*****.openai.azure.com/openai
yes above link works fine , thanks
