### ISSUE TITLE
Can We Use Storage Feature?

### ISSUE THREAD

**Issue by PBomermustekiin** [davidmigloz/langchain_dart#623]
### Idea or request for content:

Hi,

Am i able to send chats to openAI and fetch them from storage with this package? So basically i wanna create history part for old chats and achieve them.

**Comment by davidmigloz** [comment]
Currently, we only have support for storing the history in-memory:
https://langchaindart.dev/#/modules/memory/memory

But, it should be possible to do a custom implementation to persist the history to disk as @Nana-Kwame-bot mentions. #171 does that with Firestore.

Chat history is an area where we still need to improve the framework.
