### ISSUE TITLE
Add support for MapReduceChain

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#65]

**Comment by ITP2023** [comment]
Are these the ones?
- Python: https://github.com/langchain-ai/langchain/blob/c2d1d903fa35b91018b4d777db2b008fcbaa9fbc/langchain/chains/mapreduce.py
- Javascript: https://github.com/langchain-ai/langchainjs/blob/main/langchain/src/chains/combine_docs_chain.ts
