### ISSUE TITLE
Add support for Supabase VectorStore

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#69]
https://github.com/supabase/supabase-flutter/issues/489#issuecomment-1628504192

https://cookbook.openai.com/examples/vector_databases/supabase/readme

**Comment by matteodg** [comment]
Hi @davidmigloz , I'd like to take care of this task, is that OK?

**Comment by davidmigloz** [comment]
Hey @matteodg !

Thanks for your interest in contributing 🙂

@luisredondo was going to start working on it (not sure if he started implementing it yet), but I see you already made quite some progress so go for it!

**Comment by davidmigloz** [comment]
Actually, @luisredondo is telling me that he already started implementing it as well (my bad that I didn't update the ticket). It'd be good to try to sync/merge your changes and his changes. Are you in [LangChain.dart Discord](https://discord.gg/x4qbhqecVR) @matteodg? We can discuss it in the #contributing channel.

**Comment by luisredondo** [comment]
Hey @matteodg! I have been researching how to implement this appropriately and can offer some input if needed. We can sync via Discord. @davidmigloz provided the link above. You already made a good amount of progress, so I don't mind if you take over it. But here I am if you need a hand!

**Comment by matteodg** [comment]
Hi @luisredondo! I'm basically converting to Dart from the Python LangChain (but actually the JS one might be a better source, easier for me at least as I'm more a Java dev). Let me know any input you have or any work you already have done. Thanks!

**Comment by matteodg** [comment]
I found a few inconsistencies between Python LangChain and the JS one:

- Python Langchain assumes the `documents` table has an `id` of type `UUID`, see https://python.langchain.com/docs/templates/self-query-supabase#setup-supabase-database
- JS LangChain assume the `documents` table has an `id` of type `BIGSERIAL` and has the `match_count` in the `match_documents` function, see https://js.langchain.com/docs/integrations/vectorstores/supabase

I used the JS LangChain definition for the moment.

**Comment by matteodg** [comment]
Hi @davidmigloz and @luisredondo, the PR is ready for you to review!

I slightly changed the `match_documents` functions: it now contains also the `match_threshold` (see the blog entry [Storing OpenAI embeddings in Postgres with pgvector](https://supabase.com/blog/openai-embeddings-postgres-vector)), so we can filter the results by threshold directly in Supabase instead of filtering them locally.

**Comment by davidmigloz** [comment]
@matteodg  awesome, thank you very much!

Can you open a PR from your repo to this repo? 
I'll review it tomorrow

**Comment by matteodg** [comment]
Here it is https://github.com/davidmigloz/langchain_dart/pull/318

**Comment by davidmigloz** [comment]
Released 🚀
https://pub.dev/packages/langchain_supabase/changelog#001

Docs: https://langchaindart.com/#/modules/retrieval/vector_stores/integrations/supabase
