### ISSUE TITLE
Add support for RouterChain

### ISSUE THREAD

**Issue by davidmigloz** [davidmigloz/langchain_dart#85]
https://github.com/langchain-ai/langchain/blob/master/libs/langchain/langchain/chains/router/base.py

- Allows to route an input to a chain or another depending on the input.
- Useful when you have different subchains specialized for different types of inputs.
- Types:
  * `LLMRouterChain`: A router chain that uses an LLM chain to perform routing.
  * `EmbeddingRouterChain`:  Chain that uses embeddings to route between options.

![image](https://github.com/davidmigloz/langchain_dart/assets/6546265/611c6f31-ad3b-4fe7-b3e8-f8797a51cf5c)

**Comment by mauricepoirrier** [comment]
Hey @davidmigloz sorry the delay, i'll start it this week as we launched a product and it's been hell to make time for this!

Up for grabs if someone wants it though

**Comment by davidmigloz** [comment]
hey @mauricepoirrier!

I hope you had a smooth and successful launch 🚀

Actually, after releasing [LangChain Expression Language (LCEL)](https://langchaindart.com/#/expression_language/expression_language) this ticket is kind of deprecated. We should probably repurpose it to "Add support for RunnableBranch". 

These are the docs of RunnableBranch:
- https://twitter.com/LangChainAI/status/1704156731058557104
- https://python.langchain.com/docs/expression_language/how_to/routing
- https://js.langchain.com/docs/expression_language/how_to/routing

**Comment by davidmigloz** [comment]
hey @mauricepoirrier!

I hope you had a smooth and successful launch 🚀

Actually, after releasing [LangChain Expression Language (LCEL)](https://langchaindart.com/#/expression_language/expression_language) this ticket is kind of deprecated. We should probably repurpose it to "Add support for RunnableBranch". 

These are the docs of RunnableBranch:
- https://twitter.com/LangChainAI/status/1704156731058557104
- https://python.langchain.com/docs/expression_language/how_to/routing
- https://js.langchain.com/docs/expression_language/how_to/routing

**Comment by mauricepoirrier** [comment]
Thank you @davidmigloz ! 
Sounds great, down for it. Should we close this issue or rename it?

**Comment by davidmigloz** [comment]
I've created a new ticket and I'll close this one.

https://github.com/davidmigloz/langchain_dart/issues/169

Drop a comment in the new ticket and I'll assign it to you 🙂
