### ISSUE TITLE
Improve RetrievalQAChain API documentation 

### ISSUE THREAD

**Issue by mirkancal** [davidmigloz/langchain_dart#95]
### System Info

Using langchain 0.0.5 on Flutter 3.10.6

### Related Components

- [ ] doc-loaders
- [ ] doc-transformers
- [ ] prompts
- [ ] llms
- [ ] chat-models
- [ ] output-parsers
- [X] chains
- [ ] memory
- [ ] stores
- [ ] embeddings
- [ ] retrievers
- [ ] agents

### Reproduction
```
  final store = await MemoryVectorStore.fromDocuments(
      documents: chunks,
      embeddings: OpenAIEmbeddings(apiKey: Env.apiKey),
    );
    final chain  =  RetrievalQAChain.fromLlm(
      llm: llm,
      retriever: VectorStoreRetriever(
        vectorStore: store,
        k: 10,
      ),
    );
    
    chain.run(question);
```

Calling chain.run throws exception above on the title.

([unknown] run only supports one key output key. Got {result, source_documents})

I'm very new to langchain but seems like there are few contradicted code pieces.

In retrieval_qa.dart, L:69 overrides outputKeys:
```
  @override
  Set<String> get outputKeys => {
        outputKey,
        sourceDocumentsOutputKey,
      };
```

But in chains/base.dart, getter of runOutputKey throws exception when length is not 1.

```
  String get runOutputKey {
    if (outputKeys.length != 1) {
      throw LangChainException(
        message: '`run` only supports one key output key. Got $outputKeys',
      );
    }
    return outputKeys.first;
  }
```

### Expected behavior

It works when I delete second element from the line below, but not sure if it will have any side effects.

```
  @override
  Set<String> get outputKeys => {
        outputKey,
        sourceDocumentsOutputKey,
      };
```

**Comment by davidmigloz** [comment]
Hey @mirkancal,

The `run` method of a chain can only be used if the chain returns a single string output. `RetrievalQAChain` returns two outputs (two entries in the output map):
- In `result` (or the key you provide in `outputKey`): it returns the answer to your question.
- In `source_documents`: it returns the documents used to answer your question.

For these types of chains that return multiple values, you can only use their `call` method. In your case:
```dart
final store = await MemoryVectorStore.fromDocuments(
  documents: chunks,
  embeddings: OpenAIEmbeddings(apiKey: Env.apiKey),
);
final chain  =  RetrievalQAChain.fromLlm(
  llm: llm,
  retriever: VectorStoreRetriever(
    vectorStore: store,
    k: 10,
  ),
);

final res = await chain.call({RetrievalQAChain.defaultInputKey: 'What did I say?'});
final answer = res[RetrievalQAChain.defaultOutputKey];
final docs = res[RetrievalQAChain.sourceDocumentsOutputKey];
```

I will improve the documentation of the chain to clarify it. Thanks for asking the question.

**Comment by davidmigloz** [comment]
I've improved the docs in this PR: https://github.com/davidmigloz/langchain_dart/pull/96/files
Also, the error message is more helpful now:
<img width="648" alt="image" src="https://github.com/davidmigloz/langchain_dart/assets/6546265/cc040bdc-7a1c-4c2c-b000-f9c77bc46268">

Let me know if it's clear to you 🙂

**Comment by mirkancal** [comment]
Thank you. Yes, suggestion in the error message makes sense and clear for me.
